[package]
name = "ts-runtime"
version = "0.1.0"
edition = "2021"
description = "typescript native runtime"

[dependencies]
anyhow = { workspace = true }
deno_core = { workspace = true }
tokio = { workspace = true }
